# Generated by Django 2.0.1 on 2018-01-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marvel_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comics',
            name='image_ref',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='comics',
            name='date_on_sale',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='comics',
            name='ean',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='comics',
            name='image_cover',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='comics',
            name='variant_d',
            field=models.TextField(blank=True),
        ),
    ]
