# Generated by Django 2.0.1 on 2018-01-19 12:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marvel_app', '0002_auto_20180119_1158'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comics',
            new_name='Comic',
        ),
    ]
