# Generated by Django 2.0.1 on 2018-01-20 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marvel_app', '0003_auto_20180119_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='searchedComic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date_on_sale', models.TextField(blank=True)),
                ('ean', models.TextField(blank=True)),
                ('variant_d', models.TextField(blank=True)),
                ('image_ref', models.URLField(blank=True)),
                ('image_cover', models.ImageField(upload_to='media/')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
