# Generated by Django 2.0.1 on 2018-01-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marvel_app', '0004_searchedcomic'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='external_id',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
