# Generated by Django 2.0.1 on 2018-01-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marvel_app', '0006_searchedcomic_external_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchedcomic',
            name='user',
        ),
        migrations.AddField(
            model_name='comic',
            name='com_discr',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='searchedComic',
        ),
    ]
