# Generated by Django 2.0.1 on 2018-01-21 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marvel_app', '0007_auto_20180121_0927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comic',
            old_name='com_discr',
            new_name='com_descr',
        ),
    ]
