# Generated by Django 2.0.1 on 2018-01-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marvel_app', '0008_auto_20180121_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='comic',
            name='date_on_sale',
            field=models.TextField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='comic',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='comic',
            name='variants',
            field=models.ManyToManyField(to='marvel_app.Variant'),
        ),
    ]
