# Generated by Django 2.0.1 on 2018-01-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marvel_app', '0014_auto_20180121_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='v_id',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
