# Generated by Django 2.0.1 on 2018-01-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marvel_app', '0015_variant_v_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
