# Generated by Django 2.0.1 on 2018-01-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marvel_app', '0016_comic_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='image_cover',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
