# Generated by Django 2.0.1 on 2018-01-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marvel_app', '0017_auto_20180121_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComicImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('comic', models.ForeignKey(on_delete=True, related_name='images', to='marvel_app.Comic')),
            ],
        ),
    ]
