# Generated by Django 2.0.1 on 2018-01-22 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marvel_app', '0020_comic_variant_variant_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comic',
            options={'verbose_name_plural': 'Comics'},
        ),
        migrations.AlterModelOptions(
            name='comic_variant',
            options={'verbose_name_plural': 'Comic variants'},
        ),
        migrations.AlterModelOptions(
            name='comicimage',
            options={'verbose_name_plural': 'Comic images'},
        ),
        migrations.AlterField(
            model_name='comic_variant',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marvel_app.Comic'),
        ),
    ]
