# Generated by Django 2.0.1 on 2018-01-22 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marvel_app', '0021_auto_20180122_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marvel_app.Category')),
            ],
        ),
        migrations.AlterField(
            model_name='comic_variant',
            name='variant',
            field=models.ForeignKey(on_delete=None, to='marvel_app.Comic'),
        ),
        migrations.AlterField(
            model_name='comicimage',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
