# Generated by Django 2.0.1 on 2018-01-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marvel_app', '0022_auto_20180122_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.AlterField(
            model_name='comic',
            name='com_descr',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='comicimage',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
