# Generated by Django 2.0.1 on 2018-01-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marvel_app', '0023_auto_20180123_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='com_descr',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='comic',
            name='ean',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='comic',
            name='variant_d',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
