# Generated by Django 2.0.1 on 2018-01-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marvel_app', '0024_auto_20180123_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='ean',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
