# Generated by Django 2.0.1 on 2018-01-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marvel_app', '0025_auto_20180123_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comic',
            name='com_descr',
        ),
        migrations.AlterField(
            model_name='comic',
            name='date_on_sale',
            field=models.CharField(blank=True, max_length=10, verbose_name='Date of sales start'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='ean',
            field=models.CharField(blank=True, max_length=100, verbose_name='EAN'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='external_id',
            field=models.IntegerField(blank=True, verbose_name='External ID'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='Should comic be hidden or not'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='image_cover',
            field=models.ImageField(blank=True, upload_to='media/', verbose_name='Cover image field'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='image_ref',
            field=models.URLField(blank=True, verbose_name='Cover source link'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='variant_d',
            field=models.CharField(blank=True, max_length=100, verbose_name='Current variant description'),
        ),
    ]
