# Generated by Django 2.0.1 on 2018-01-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marvel_app', '0026_auto_20180123_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='com_descr',
            field=models.TextField(blank=True, verbose_name='Comic short description'),
        ),
    ]
